### ISSUE TITLE
Move the init functions from index.html to a entry script file

### ISSUE THREAD

**Issue by Dgaduin** [742617000027/farverona-sectormap#1]
Quite a few bits of script are in tags in the html - might make life a bit easier to put them in a `index.js` for a singular entry point.

**Comment by 742617000027** [comment]
Definitely! Would that be included in the footer of index.html then? Tried moving those bits of script to utils.js before but it broke things 😅

**Comment by Dgaduin** [comment]
Hmmm, I'll test it out tag by tag and see if I can make it work - I'll probably hide it behind document ready event, to make sure everything else is done.
